version: '3.8'
services:
  app:
    build: .
    ports:
      - "10000:10000"
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=StudentManagementDb;Username=postgres;Password=password
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - postgres
  
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=StudentManagementDb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: